---
build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Homebox"
  org.opencontainers.image.description: "Inventory management system for Home Assistant"
  org.opencontainers.image.source: "https://github.com/Crafter-Y/homebox-addon"
  org.opencontainers.image.licenses: "CC-BY-4.0"
